### ISSUE TITLE
Parallel coordinate plot examples are outdated and use very bad Python style

### ISSUE THREAD

**Issue by renatobellotti** [plotly/plotly.py-docs#136]
Outdated
========
When I try to run
```python
import plotly.plotly as py
```

as written in the [examples ](https://plot.ly/pandas/parallel-coordinates-plot/), I get the following error:
```
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```

**Solution**: Use
```python
import plotly
```
instead.

Unpythonic code
=============
The [examples ](https://plot.ly/pandas/parallel-coordinates-plot/) are very unpythonic. I suggest changing the code to make use of ```dict``` literals.

I just give the example of the second code, the rest is analogue.

This is not a purely stylistic issue. The identifier ```range``` is a Python builtin command that is overwritten by the snipped below.

**Code now**:
```python
data = [
    go.Parcoords(
        line = dict(color = df['species_id'],
                   colorscale = [[0,'#D7C16B'],[0.5,'#23D8C3'],[1,'#F3F10F']]),
        dimensions = list([
            dict(range = [0,8],
                constraintrange = [4,8],
                label = 'Sepal Length', values = df['sepal_length']),
            dict(range = [0,8],
                label = 'Sepal Width', values = df['sepal_width']),
            dict(range = [0,8],
                label = 'Petal Length', values = df['petal_length']),
            dict(range = [0,8],
                label = 'Petal Width', values = df['petal_width'])
        ])
    )
]
```

**Proposed improvement**:
```python
data = [
    go.Parcoords(
        line = {
            'color': df['species_id'],
            'colorscale': [[0,'#D7C16B'],[0.5,'#23D8C3'],[1,'#F3F10F']]
        },
        dimensions = [
            {
                'range': [0,8],
                'constraintrange': [4,8],
                'label': 'Sepal Length',
                'values': df['sepal_length']
            },
            {
                'range': [0,8],
                'label': 'Sepal Width',
                'values': df['sepal_width']
            },
            {
                'range': [0,8],
                'label': 'Petal Length',
                'values': df['petal_length']
            },
            {
                'range': [0,8],
                'label': 'Petal Width',
                'values': df['petal_width']
            }
        ]
    )
]
```

**Comment by nicolaskruchten** [comment]
Thanks for the feedback! We're actually in the process of deprecating the `/pandas/*` family of documentation pages in favour of the new version-4 `/python/*` family of pages, so this page https://plot.ly/python/parallel-coordinates-plot/ will be the new landing page for those URLs.

**Comment by renatobellotti** [comment]
Thank you for the fast answer! :)

**Comment by nicolaskruchten** [comment]
Ah, I just noticed that your comments re `range` apply to our 'new' docs as well... Can you elaborate a bit on the nature of the problem? From what I can tell, using `range` as a kwarg to `dict` doesn't do anything strange...

![image](https://user-images.githubusercontent.com/203523/66501891-44afaf80-ea92-11e9-9073-37e26892db21.png)

**Comment by renatobellotti** [comment]
Perhaps parameters don't count as names, so it is probably fine. But range is a key word, so I wouldn't use it as a variable name. When it us used as a string literal, we're on the safe side in any case.
