### ISSUE TITLE
Broken "see also" links

### ISSUE THREAD

**Issue by joshuatshaffer** [plotly/plotly.py-docs#140]
The links in the "See also" section of https://plot.ly/python/streamline-plots/ cause 404 errors. This appears to be an error in the relative URLs given. For example the currently used `href="./quiver-plots/"` leads to the page https://plot.ly/python/streamline-plots/quiver-plots/ which does not exist, but `href="../quiver-plots/"` leads to the page https://plot.ly/python/quiver-plots/ which does exist.

**Comment by emmanuelle** [comment]
Thank you we have to fix this!

**Comment by nicolaskruchten** [comment]
Fixed! thanks for the bug report :)

**Comment by joshuatshaffer** [comment]
You're welcome, I'm happy to help. I just tested it myself and it's working great.
