### ISSUE TITLE
Remove mentions of "tidy dataframes" in px paragraphs

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py-docs#147]

**Comment by nicolaskruchten** [comment]
I think that #131 goes too far in removing these mentions and actually now important pages like https://plot.ly/python/line-and-scatter/ don't have a link to either an explanation of Tidy Data or https://plot.ly/python/px-arguments/ ...

We need to do a pass here that clearly indicates that PX *operates* on tidy dataframes, and it accepts either those dataframes directly, or its constituent parts that are assembled into a dataframe for you.
